import moment from 'moment';

//format day
export const days = [moment().format('ddd, MMM D'), moment().add(1, 'days').format('ddd, MMM D'), moment().add(2, 'days').format('ddd, MMM D'), moment().add(3, 'days').format('ddd, MMM D'), moment().add(4, 'days').format('ddd, MMM D'), moment().add(5, 'days').format('ddd, MMM D'), moment().add(6, 'days').format('ddd, MMM D')];
//format time
export const times = ['7:00 AM', '9:00 AM', '11:10 AM', '12:00 AM', '1:50 PM', '4:30 PM', '6:00 PM', '8:10 PM', '10:50 PM'];

// export const movies = [
//     {
//         id:1,
//         title: 'La La Land',
//         poster: 'https://i.imgur.com/po7UezG.jpg',
//         genre: 'Drama/Romance',
//         days,
//         times,
//     },
//     {
//         id:2,
//         title: 'Paterson',
//         poster: 'https://i.imgur.com/pE0C9E0.jpg',
//         genre: 'Drama/Comedy',
//         days,
//         times,
//     },
//     {
//         id:3,
//         title: 'Jackie',
//         poster: 'https://i.imgur.com/VqUi1sw.jpg',
//         genre: 'Drama/Biography',
//         days,
//         times,
//     },
//     {
//         id:4,
//         title: 'Lo and Behold Reveries of the Connected World',
//         poster: 'https://i.imgur.com/s106X7S.jpg',
//         genre: 'Documentary',
//         days,
//         times,
//     },
//     {
//         id:5,
//         title: '10 Cloverfield Lane',
//         poster: 'https://i.imgur.com/kV2BVdH.jpg',
//         genre: 'Drama',
//         days,
//         times,
//     },
//     {
//         id:6,
//         title: 'Birth of a Nation',
//         poster: 'https://i.imgur.com/a6HJj8S.jpg',
//         genre: 'Fantasy/Myster',
//         days,
//         times,
//     },
//     {
//         id:7,
//         title: 'De Palma',
//         poster: 'https://i.imgur.com/oOIa73M.jpg',
//         genre: 'Documentary',
//         days,
//         times,
//     },
//     {
//         id:8,
//         title: 'Doctor Strange',
//         poster: 'https://i.imgur.com/kyHDVOk.jpg',
//         genre: 'Fantasy/Science Fiction',
//         days,
//         times,
//     },
//     {
//         id:9,
//         title: 'Eddie the Eagle',
//         poster: 'https://i.imgur.com/GNrdAuF.jpg',
//         genre: 'Drama/Sport',
//         days,
//         times,
//     },
//     {
//         id:10,
//         title: 'Pride and prejudice and zombies',
//         poster: 'https://i.imgur.com/KhbG0Lw.jpg',
//         genre: 'Thriller/Action',
//         days,
//         times,
//     },
//     {
//         id:11,
//         title: 'Finding Dory',
//         poster: 'https://i.imgur.com/BTexHYJ.jpg',
//         genre: 'Comedy/Adventure',
//         days,
//         times,
//     },
//     {
//         id:12,
//         title: 'Green Room',
//         poster: 'https://i.imgur.com/Q0Ysh7L.jpg',
//         genre: 'Crime/Thriller',
//         days,
//         times,
//     },
//     {
//         id:13,
//         title: 'Kubo and the Two Strings',
//         poster: 'https://i.imgur.com/uTFCKZc.jpg',
//         genre: 'Fantasy/Adventure',
//         days,
//         times,
//     },
//     {
//         id:14,
//         title: 'In a Valley of Violence',
//         poster: 'https://i.imgur.com/DTtJ62G.jpg',
//         genre: 'Drama/Western',
//         days,
//         times,
//     },
//     {
//         id:15,
//         title: 'O.J.: Made in America',
//         poster: 'https://i.imgur.com/T8uc6x8.jpg',
//         genre: 'Documentary',
//         days,
//         times,
//     },
//     {
//         id:16,
//         title: 'Rogue One: A Star Wars Story',
//         poster: 'https://i.imgur.com/zOF2iYc.jpg',
//         genre: 'Science Fiction/Action',
//         days,
//         times,
//     },
//     {
//         id:17,
//         title: 'Sing Street',
//         poster: 'https://i.imgur.com/C3ExEb6.jpg',
//         genre: 'Drama/Romance',
//         days,
//         times,
//     },
//     {
//         id:18,
//         title: 'Zoolander 2',
//         poster: 'https://i.imgur.com/ejlIijD.jpg',
//         genre: 'Comedy',
//         days,
//         times,
//     },
// ]